services:
  backend:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./:/api
    env_file:
      - ./.env
    environment:
      - SQL_HOST=db
    # Use the CMD from the Dockerfile (gunicorn) or specify explicitly below:
    # command: gunicorn your_project.wsgi:application --bind 0.0.0.0:8000

    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgis/postgis:17-3.5
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init-postgis.sh:/docker-entrypoint-initdb.d/init-postgis.sh
    ports:
      - 5432:5432
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=${SQL_DATABASE}
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${SQL_USER} -d ${SQL_DATABASE}']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db-data:
