# Generated by Django 5.2.7 on 2025-11-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_cashier_id_remove_client_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="collected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
