# Generated by Django 5.2.7 on 2025-12-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_cart_collected_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="city",
            field=models.CharField(blank=True, help_text="Ville", max_length=100),
        ),
        migrations.AddField(
            model_name="shop",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Latitude (coordonnées GPS)",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="shop",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Longitude (coordonnées GPS)",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="shop",
            name="postal_code",
            field=models.CharField(
                blank=True, help_text="Code postal pour filtrer l'autocomplétion", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="shop",
            name="street_name",
            field=models.CharField(blank=True, help_text="Nom de la rue", max_length=200),
        ),
        migrations.AddField(
            model_name="shop",
            name="street_number",
            field=models.CharField(blank=True, help_text="Numéro de rue", max_length=20),
        ),
    ]
