# Generated by Django 5.2.7 on 2025-12-21 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_cart_collected_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carts",
                to="api.recipient",
            ),
        ),
    ]
