# Generated by Django 5.2.7 on 2025-12-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_shop_city_shop_latitude_shop_longitude_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shop",
            name="address",
        ),
        migrations.AlterField(
            model_name="shop",
            name="city",
            field=models.CharField(blank=True, help_text="City", max_length=100),
        ),
        migrations.AlterField(
            model_name="shop",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Latitude (GPS coordinates)",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Longitude (GPS coordinates)",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="postal_code",
            field=models.CharField(blank=True, help_text="Postal code", max_length=10),
        ),
        migrations.AlterField(
            model_name="shop",
            name="street_name",
            field=models.CharField(blank=True, help_text="Street name", max_length=200),
        ),
        migrations.AlterField(
            model_name="shop",
            name="street_number",
            field=models.CharField(blank=True, help_text="Street number", max_length=20),
        ),
    ]
