# Generated by Django 5.2.7 on 2025-12-21 13:10

from django.db import migrations


def set_pending_carts_recipient_to_none(apps, schema_editor):
    """Set recipient to None for all carts with PENDING status"""
    Cart = apps.get_model("api", "Cart")
    Cart.objects.filter(status="PENDING").update(recipient=None)


def reverse_migration(apps, schema_editor):
    """This migration is not reversible as we cannot restore the original recipient"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_make_cart_recipient_nullable"),
    ]

    operations = [
        migrations.RunPython(set_pending_carts_recipient_to_none, reverse_migration),
    ]
