# Generated by Django 5.2.7 on 2025-12-21 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_set_pending_carts_recipient_to_none"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="status",
        ),
    ]
