# Generated by Django 5.2.7 on 2025-12-24 16:50

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_remove_shop_address_alter_shop_city_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shop",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="shop",
            name="longitude",
        ),
        migrations.AddField(
            model_name="shop",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                geography=True,
                help_text="Geographic coordinates (longitude, latitude)",
                null=True,
                srid=4326,
            ),
        ),
    ]
