# Generated by Django 5.2.7 on 2025-12-29 18:27

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_remove_cart_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shop",
            name="address",
        ),
        migrations.RemoveField(
            model_name="socialcenter",
            name="address",
        ),
        migrations.AddField(
            model_name="shop",
            name="city",
            field=models.CharField(blank=True, help_text="City", max_length=100),
        ),
        migrations.AddField(
            model_name="shop",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                geography=True,
                help_text="Geographic coordinates (longitude, latitude)",
                null=True,
                srid=4326,
            ),
        ),
        migrations.AddField(
            model_name="shop",
            name="postal_code",
            field=models.CharField(blank=True, help_text="Postal code", max_length=10),
        ),
        migrations.AddField(
            model_name="shop",
            name="street_name",
            field=models.CharField(blank=True, help_text="Street name", max_length=200),
        ),
        migrations.AddField(
            model_name="shop",
            name="street_number",
            field=models.CharField(blank=True, help_text="Street number", max_length=20),
        ),
        migrations.AddField(
            model_name="socialcenter",
            name="city",
            field=models.CharField(blank=True, help_text="City", max_length=100),
        ),
        migrations.AddField(
            model_name="socialcenter",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                geography=True,
                help_text="Geographic coordinates (longitude, latitude)",
                null=True,
                srid=4326,
            ),
        ),
        migrations.AddField(
            model_name="socialcenter",
            name="postal_code",
            field=models.CharField(blank=True, help_text="Postal code", max_length=10),
        ),
        migrations.AddField(
            model_name="socialcenter",
            name="street_name",
            field=models.CharField(blank=True, help_text="Street name", max_length=200),
        ),
        migrations.AddField(
            model_name="socialcenter",
            name="street_number",
            field=models.CharField(blank=True, help_text="Street number", max_length=20),
        ),
    ]
