# Generated by Django 5.2.7 on 2026-01-12 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_remove_cart_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="social_worker",
            field=models.ForeignKey(
                default="",
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shops",
                to="api.socialworker",
            ),
        ),
    ]
