# Generated by Django 5.2.7 on 2026-01-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_article_brand_label_article_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="brand_label",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="article",
            name="img_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="article",
            name="thumb_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
    ]
