# Generated by Django 5.2.7 on 2026-01-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_alter_article_brand_label_alter_article_img_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="name",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
