# Generated by Django 5.2.7 on 2026-01-24 11:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_alter_shop_social_worker"),
        ("api", "0011_alter_article_name"),
    ]

    operations = []
