# Generated by Django 5.2.7 on 2026-02-08 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_alter_article_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cashier",
            options={"verbose_name": "Cashier", "verbose_name_plural": "Cashiers"},
        ),
        migrations.AddField(
            model_name="cashier",
            name="is_shop_manager",
            field=models.BooleanField(
                default=False, help_text="Designates whether this cashier can manage other cashiers"
            ),
        ),
        migrations.AlterField(
            model_name="cashier",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="cashiers", to="api.shop"
            ),
        ),
    ]
