# Generated by Django 5.2.7 on 2026-01-24 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_merge_20260124_1147"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="address",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="shop",
            name="social_worker",
            field=models.ForeignKey(
                default="0", on_delete=django.db.models.deletion.CASCADE, related_name="shops", to="api.socialworker"
            ),
        ),
    ]
