# Generated by Django 5.2.7 on 2026-02-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_alter_cashier_options_cashier_is_shop_manager_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialworker",
            name="is_social_admin",
            field=models.BooleanField(
                default=False, help_text="Designates whether this social worker can create users and shops."
            ),
        ),
        migrations.AlterField(
            model_name="cashier",
            name="is_shop_manager",
            field=models.BooleanField(
                default=False, help_text="Designates whether this cashier can manage other cashiers."
            ),
        ),
    ]
