# Generated by Django 5.2.7 on 2026-04-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_socialworker_is_social_admin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cashier",
            name="is_shop_manager",
            field=models.BooleanField(
                default=False, help_text="Designates whether this cashier can manage other cashiers."
            ),
        ),
    ]
