# Generated by Django 5.2.7 on 2026-04-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_socialworker_is_social_admin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
