# Generated by Django 5.2.7 on 2026-01-24 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_shop_address_alter_shop_social_worker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="client",
            field=models.ForeignKey(
                default="0", on_delete=django.db.models.deletion.CASCADE, related_name="articles", to="api.client"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="shop",
            field=models.ForeignKey(
                default="0", on_delete=django.db.models.deletion.CASCADE, related_name="articles", to="api.shop"
            ),
        ),
    ]
