# Generated by Django 5.2.7 on 2026-05-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_cart_created_at"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["shop", "cart"], name="article_shop_cart_idx"),
        ),
    ]
