# Generated by Django 5.2.7 on 2026-05-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_cart_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"verbose_name": "article", "verbose_name_plural": "articles"},
        ),
        migrations.AlterModelOptions(
            name="cart",
            options={"verbose_name": "panier", "verbose_name_plural": "paniers"},
        ),
        migrations.AlterModelOptions(
            name="cashier",
            options={"verbose_name": "caissier", "verbose_name_plural": "caissiers"},
        ),
        migrations.AlterModelOptions(
            name="client",
            options={"verbose_name": "client", "verbose_name_plural": "clients"},
        ),
        migrations.AlterModelOptions(
            name="recipient",
            options={"verbose_name": "bénéficiaire", "verbose_name_plural": "bénéficiaires"},
        ),
        migrations.AlterModelOptions(
            name="shop",
            options={"verbose_name": "magasin", "verbose_name_plural": "magasins"},
        ),
        migrations.AlterModelOptions(
            name="socialcenter",
            options={"verbose_name": "centre social", "verbose_name_plural": "centres sociaux"},
        ),
        migrations.AlterModelOptions(
            name="socialworker",
            options={"verbose_name": "travailleur social", "verbose_name_plural": "travailleurs sociaux"},
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user can log into this admin site.",
                verbose_name="staff",
            ),
        ),
    ]
