# Generated by Django 5.2.7 on 2026-05-10 17:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_alter_article_options_alter_cart_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cashier",
            options={"verbose_name": "vendeur", "verbose_name_plural": "vendeurs"},
        ),
    ]
