# Generated by Django 5.2.7 on 2026-05-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0017_alter_cashier_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="notified_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date et heure de la dernière notification envoyée au bénéficiaire.",
                null=True,
                verbose_name="notifié le",
            ),
        ),
    ]
