# Generated by Django 5.2.11 on 2026-06-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0018_cart_notified_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="name",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
